name: Lint test and deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: start linting
        run: npm run lint